### ISSUE TITLE
CORS Header Setting

### ISSUE THREAD

**Issue by tqma113** [didi/Tips#3]
https://github.com/didi/Tips/blob/8b189185b039b8a65197158440ab6679e450bff9/tips-web/app.js#L12

`Access-Control-Allow-Origin: '*'`时 `Access-Control-Allow-Credentials: true` 应该是无效的

https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS
https://stackoverflow.com/questions/19743396/cors-cannot-use-wildcard-in-access-control-allow-origin-when-credentials-flag-i

**Comment by lwjcode** [comment]
谢谢指出，学到了！
